# Generated by Django 3.1.1 on 2020-12-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20201210_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='created_at',
            new_name='received_at',
        ),
    ]
